# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.13.x

go_import_path: github.com/MuShare/pluto

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - export GO111MODULE=on; go test -v -race ./...  # Run all the tests with the race detector enabled