// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Applications             string
	DeviceApps               string
	OauthAuthorizationCodes  string
	OauthClients             string
	RbacRoleScopes           string
	RbacRoles                string
	RbacScopes               string
	RbacUserApplicationRoles string
	RefreshTokens            string
	Salts                    string
	Users                    string
}{
	Applications:             "applications",
	DeviceApps:               "device_apps",
	OauthAuthorizationCodes:  "oauth_authorization_codes",
	OauthClients:             "oauth_clients",
	RbacRoleScopes:           "rbac_role_scopes",
	RbacRoles:                "rbac_roles",
	RbacScopes:               "rbac_scopes",
	RbacUserApplicationRoles: "rbac_user_application_roles",
	RefreshTokens:            "refresh_tokens",
	Salts:                    "salts",
	Users:                    "users",
}
