// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Applications   string
	DeviceApps     string
	RbacRoleScopes string
	RbacRoles      string
	RbacUserRoles  string
	RefreshTokens  string
	Salts          string
	Scopes         string
	Users          string
}{
	Applications:   "applications",
	DeviceApps:     "device_apps",
	RbacRoleScopes: "rbac_role_scopes",
	RbacRoles:      "rbac_roles",
	RbacUserRoles:  "rbac_user_roles",
	RefreshTokens:  "refresh_tokens",
	Salts:          "salts",
	Scopes:         "scopes",
	Users:          "users",
}
