// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// HistoryOperation is an object representing the database table.
type HistoryOperation struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	UserID    uint      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Type      string    `boil:"type" json:"type" toml:"type" yaml:"type"`

	R *historyOperationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L historyOperationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HistoryOperationColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	UserID    string
	Type      string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	UserID:    "user_id",
	Type:      "type",
}

// Generated where

var HistoryOperationWhere = struct {
	ID        whereHelperuint
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
	DeletedAt whereHelpernull_Time
	UserID    whereHelperuint
	Type      whereHelperstring
}{
	ID:        whereHelperuint{field: "`history_operations`.`id`"},
	CreatedAt: whereHelpernull_Time{field: "`history_operations`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`history_operations`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`history_operations`.`deleted_at`"},
	UserID:    whereHelperuint{field: "`history_operations`.`user_id`"},
	Type:      whereHelperstring{field: "`history_operations`.`type`"},
}

// HistoryOperationRels is where relationship names are stored.
var HistoryOperationRels = struct {
}{}

// historyOperationR is where relationships are stored.
type historyOperationR struct {
}

// NewStruct creates a new relationship struct
func (*historyOperationR) NewStruct() *historyOperationR {
	return &historyOperationR{}
}

// historyOperationL is where Load methods for each relationship are stored.
type historyOperationL struct{}

var (
	historyOperationAllColumns            = []string{"id", "created_at", "updated_at", "deleted_at", "user_id", "type"}
	historyOperationColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "user_id", "type"}
	historyOperationColumnsWithDefault    = []string{"id"}
	historyOperationPrimaryKeyColumns     = []string{"id"}
)

type (
	// HistoryOperationSlice is an alias for a slice of pointers to HistoryOperation.
	// This should generally be used opposed to []HistoryOperation.
	HistoryOperationSlice []*HistoryOperation
	// HistoryOperationHook is the signature for custom HistoryOperation hook methods
	HistoryOperationHook func(boil.Executor, *HistoryOperation) error

	historyOperationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	historyOperationType                 = reflect.TypeOf(&HistoryOperation{})
	historyOperationMapping              = queries.MakeStructMapping(historyOperationType)
	historyOperationPrimaryKeyMapping, _ = queries.BindMapping(historyOperationType, historyOperationMapping, historyOperationPrimaryKeyColumns)
	historyOperationInsertCacheMut       sync.RWMutex
	historyOperationInsertCache          = make(map[string]insertCache)
	historyOperationUpdateCacheMut       sync.RWMutex
	historyOperationUpdateCache          = make(map[string]updateCache)
	historyOperationUpsertCacheMut       sync.RWMutex
	historyOperationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var historyOperationBeforeInsertHooks []HistoryOperationHook
var historyOperationBeforeUpdateHooks []HistoryOperationHook
var historyOperationBeforeDeleteHooks []HistoryOperationHook
var historyOperationBeforeUpsertHooks []HistoryOperationHook

var historyOperationAfterInsertHooks []HistoryOperationHook
var historyOperationAfterSelectHooks []HistoryOperationHook
var historyOperationAfterUpdateHooks []HistoryOperationHook
var historyOperationAfterDeleteHooks []HistoryOperationHook
var historyOperationAfterUpsertHooks []HistoryOperationHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HistoryOperation) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HistoryOperation) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HistoryOperation) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HistoryOperation) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HistoryOperation) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HistoryOperation) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HistoryOperation) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HistoryOperation) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HistoryOperation) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historyOperationAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHistoryOperationHook registers your hook function for all future operations.
func AddHistoryOperationHook(hookPoint boil.HookPoint, historyOperationHook HistoryOperationHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		historyOperationBeforeInsertHooks = append(historyOperationBeforeInsertHooks, historyOperationHook)
	case boil.BeforeUpdateHook:
		historyOperationBeforeUpdateHooks = append(historyOperationBeforeUpdateHooks, historyOperationHook)
	case boil.BeforeDeleteHook:
		historyOperationBeforeDeleteHooks = append(historyOperationBeforeDeleteHooks, historyOperationHook)
	case boil.BeforeUpsertHook:
		historyOperationBeforeUpsertHooks = append(historyOperationBeforeUpsertHooks, historyOperationHook)
	case boil.AfterInsertHook:
		historyOperationAfterInsertHooks = append(historyOperationAfterInsertHooks, historyOperationHook)
	case boil.AfterSelectHook:
		historyOperationAfterSelectHooks = append(historyOperationAfterSelectHooks, historyOperationHook)
	case boil.AfterUpdateHook:
		historyOperationAfterUpdateHooks = append(historyOperationAfterUpdateHooks, historyOperationHook)
	case boil.AfterDeleteHook:
		historyOperationAfterDeleteHooks = append(historyOperationAfterDeleteHooks, historyOperationHook)
	case boil.AfterUpsertHook:
		historyOperationAfterUpsertHooks = append(historyOperationAfterUpsertHooks, historyOperationHook)
	}
}

// One returns a single historyOperation record from the query.
func (q historyOperationQuery) One(exec boil.Executor) (*HistoryOperation, error) {
	o := &HistoryOperation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for history_operations")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all HistoryOperation records from the query.
func (q historyOperationQuery) All(exec boil.Executor) (HistoryOperationSlice, error) {
	var o []*HistoryOperation

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HistoryOperation slice")
	}

	if len(historyOperationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all HistoryOperation records in the query.
func (q historyOperationQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count history_operations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q historyOperationQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if history_operations exists")
	}

	return count > 0, nil
}

// HistoryOperations retrieves all the records using an executor.
func HistoryOperations(mods ...qm.QueryMod) historyOperationQuery {
	mods = append(mods, qm.From("`history_operations`"))
	return historyOperationQuery{NewQuery(mods...)}
}

// FindHistoryOperation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHistoryOperation(exec boil.Executor, iD uint, selectCols ...string) (*HistoryOperation, error) {
	historyOperationObj := &HistoryOperation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `history_operations` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, historyOperationObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from history_operations")
	}

	return historyOperationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HistoryOperation) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no history_operations provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historyOperationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	historyOperationInsertCacheMut.RLock()
	cache, cached := historyOperationInsertCache[key]
	historyOperationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			historyOperationAllColumns,
			historyOperationColumnsWithDefault,
			historyOperationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(historyOperationType, historyOperationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(historyOperationType, historyOperationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `history_operations` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `history_operations` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `history_operations` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, historyOperationPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into history_operations")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == historyOperationMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for history_operations")
	}

CacheNoHooks:
	if !cached {
		historyOperationInsertCacheMut.Lock()
		historyOperationInsertCache[key] = cache
		historyOperationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the HistoryOperation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HistoryOperation) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	historyOperationUpdateCacheMut.RLock()
	cache, cached := historyOperationUpdateCache[key]
	historyOperationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			historyOperationAllColumns,
			historyOperationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update history_operations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `history_operations` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, historyOperationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(historyOperationType, historyOperationMapping, append(wl, historyOperationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update history_operations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for history_operations")
	}

	if !cached {
		historyOperationUpdateCacheMut.Lock()
		historyOperationUpdateCache[key] = cache
		historyOperationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q historyOperationQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for history_operations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for history_operations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HistoryOperationSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historyOperationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `history_operations` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, historyOperationPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in historyOperation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all historyOperation")
	}
	return rowsAff, nil
}

var mySQLHistoryOperationUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HistoryOperation) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no history_operations provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historyOperationColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLHistoryOperationUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	historyOperationUpsertCacheMut.RLock()
	cache, cached := historyOperationUpsertCache[key]
	historyOperationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			historyOperationAllColumns,
			historyOperationColumnsWithDefault,
			historyOperationColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			historyOperationAllColumns,
			historyOperationPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert history_operations, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "history_operations", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `history_operations` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(historyOperationType, historyOperationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(historyOperationType, historyOperationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for history_operations")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == historyOperationMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(historyOperationType, historyOperationMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for history_operations")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for history_operations")
	}

CacheNoHooks:
	if !cached {
		historyOperationUpsertCacheMut.Lock()
		historyOperationUpsertCache[key] = cache
		historyOperationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single HistoryOperation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HistoryOperation) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HistoryOperation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), historyOperationPrimaryKeyMapping)
	sql := "DELETE FROM `history_operations` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from history_operations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for history_operations")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q historyOperationQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no historyOperationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from history_operations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for history_operations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HistoryOperationSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(historyOperationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historyOperationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `history_operations` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, historyOperationPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from historyOperation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for history_operations")
	}

	if len(historyOperationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HistoryOperation) Reload(exec boil.Executor) error {
	ret, err := FindHistoryOperation(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HistoryOperationSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HistoryOperationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historyOperationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `history_operations`.* FROM `history_operations` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, historyOperationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HistoryOperationSlice")
	}

	*o = slice

	return nil
}

// HistoryOperationExists checks if the HistoryOperation row exists.
func HistoryOperationExists(exec boil.Executor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `history_operations` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if history_operations exists")
	}

	return exists, nil
}
