// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Applications", testApplicationsUpsert)

	t.Run("Bindings", testBindingsUpsert)

	t.Run("DeviceApps", testDeviceAppsUpsert)

	t.Run("Migrations", testMigrationsUpsert)

	t.Run("OauthAuthorizationCodes", testOauthAuthorizationCodesUpsert)

	t.Run("OauthClients", testOauthClientsUpsert)

	t.Run("RbacRoleScopes", testRbacRoleScopesUpsert)

	t.Run("RbacRoles", testRbacRolesUpsert)

	t.Run("RbacScopes", testRbacScopesUpsert)

	t.Run("RbacUserApplicationRoles", testRbacUserApplicationRolesUpsert)

	t.Run("RefreshTokens", testRefreshTokensUpsert)

	t.Run("Salts", testSaltsUpsert)

	t.Run("Users", testUsersUpsert)
}
