// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOauthAuthorizationCodes(t *testing.T) {
	t.Parallel()

	query := OauthAuthorizationCodes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOauthAuthorizationCodesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthAuthorizationCodesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OauthAuthorizationCodes().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthAuthorizationCodesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OauthAuthorizationCodeSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthAuthorizationCodesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OauthAuthorizationCodeExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OauthAuthorizationCode exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OauthAuthorizationCodeExists to return true, but got false.")
	}
}

func testOauthAuthorizationCodesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	oauthAuthorizationCodeFound, err := FindOauthAuthorizationCode(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if oauthAuthorizationCodeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOauthAuthorizationCodesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OauthAuthorizationCodes().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testOauthAuthorizationCodesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OauthAuthorizationCodes().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOauthAuthorizationCodesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	oauthAuthorizationCodeOne := &OauthAuthorizationCode{}
	oauthAuthorizationCodeTwo := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, oauthAuthorizationCodeOne, oauthAuthorizationCodeDBTypes, false, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}
	if err = randomize.Struct(seed, oauthAuthorizationCodeTwo, oauthAuthorizationCodeDBTypes, false, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = oauthAuthorizationCodeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oauthAuthorizationCodeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OauthAuthorizationCodes().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOauthAuthorizationCodesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	oauthAuthorizationCodeOne := &OauthAuthorizationCode{}
	oauthAuthorizationCodeTwo := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, oauthAuthorizationCodeOne, oauthAuthorizationCodeDBTypes, false, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}
	if err = randomize.Struct(seed, oauthAuthorizationCodeTwo, oauthAuthorizationCodeDBTypes, false, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = oauthAuthorizationCodeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oauthAuthorizationCodeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func oauthAuthorizationCodeBeforeInsertHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeAfterInsertHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeAfterSelectHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeBeforeUpdateHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeAfterUpdateHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeBeforeDeleteHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeAfterDeleteHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeBeforeUpsertHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func oauthAuthorizationCodeAfterUpsertHook(e boil.Executor, o *OauthAuthorizationCode) error {
	*o = OauthAuthorizationCode{}
	return nil
}

func testOauthAuthorizationCodesHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &OauthAuthorizationCode{}
	o := &OauthAuthorizationCode{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode object: %s", err)
	}

	AddOauthAuthorizationCodeHook(boil.BeforeInsertHook, oauthAuthorizationCodeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeBeforeInsertHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.AfterInsertHook, oauthAuthorizationCodeAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeAfterInsertHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.AfterSelectHook, oauthAuthorizationCodeAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeAfterSelectHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.BeforeUpdateHook, oauthAuthorizationCodeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeBeforeUpdateHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.AfterUpdateHook, oauthAuthorizationCodeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeAfterUpdateHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.BeforeDeleteHook, oauthAuthorizationCodeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeBeforeDeleteHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.AfterDeleteHook, oauthAuthorizationCodeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeAfterDeleteHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.BeforeUpsertHook, oauthAuthorizationCodeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeBeforeUpsertHooks = []OauthAuthorizationCodeHook{}

	AddOauthAuthorizationCodeHook(boil.AfterUpsertHook, oauthAuthorizationCodeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	oauthAuthorizationCodeAfterUpsertHooks = []OauthAuthorizationCodeHook{}
}

func testOauthAuthorizationCodesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOauthAuthorizationCodesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(oauthAuthorizationCodeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOauthAuthorizationCodesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testOauthAuthorizationCodesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OauthAuthorizationCodeSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testOauthAuthorizationCodesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OauthAuthorizationCodes().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	oauthAuthorizationCodeDBTypes = map[string]string{`ID`: `int`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`, `DeletedAt`: `timestamp`, `UserID`: `int`, `ClientID`: `int`, `AppID`: `int`, `Code`: `varchar`, `RedirectURI`: `varchar`, `ExpireAt`: `timestamp`, `Scopes`: `varchar`}
	_                             = bytes.MinRead
)

func testOauthAuthorizationCodesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(oauthAuthorizationCodePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(oauthAuthorizationCodeAllColumns) == len(oauthAuthorizationCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOauthAuthorizationCodesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(oauthAuthorizationCodeAllColumns) == len(oauthAuthorizationCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OauthAuthorizationCode{}
	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oauthAuthorizationCodeDBTypes, true, oauthAuthorizationCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(oauthAuthorizationCodeAllColumns, oauthAuthorizationCodePrimaryKeyColumns) {
		fields = oauthAuthorizationCodeAllColumns
	} else {
		fields = strmangle.SetComplement(
			oauthAuthorizationCodeAllColumns,
			oauthAuthorizationCodePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OauthAuthorizationCodeSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOauthAuthorizationCodesUpsert(t *testing.T) {
	t.Parallel()

	if len(oauthAuthorizationCodeAllColumns) == len(oauthAuthorizationCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLOauthAuthorizationCodeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OauthAuthorizationCode{}
	if err = randomize.Struct(seed, &o, oauthAuthorizationCodeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OauthAuthorizationCode: %s", err)
	}

	count, err := OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, oauthAuthorizationCodeDBTypes, false, oauthAuthorizationCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthAuthorizationCode struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OauthAuthorizationCode: %s", err)
	}

	count, err = OauthAuthorizationCodes().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
