// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRbacRoles(t *testing.T) {
	t.Parallel()

	query := RbacRoles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRbacRolesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacRolesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RbacRoles().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacRolesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RbacRoleSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacRolesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RbacRoleExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RbacRole exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RbacRoleExists to return true, but got false.")
	}
}

func testRbacRolesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rbacRoleFound, err := FindRbacRole(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rbacRoleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRbacRolesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RbacRoles().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testRbacRolesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RbacRoles().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRbacRolesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rbacRoleOne := &RbacRole{}
	rbacRoleTwo := &RbacRole{}
	if err = randomize.Struct(seed, rbacRoleOne, rbacRoleDBTypes, false, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}
	if err = randomize.Struct(seed, rbacRoleTwo, rbacRoleDBTypes, false, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = rbacRoleOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rbacRoleTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RbacRoles().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRbacRolesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rbacRoleOne := &RbacRole{}
	rbacRoleTwo := &RbacRole{}
	if err = randomize.Struct(seed, rbacRoleOne, rbacRoleDBTypes, false, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}
	if err = randomize.Struct(seed, rbacRoleTwo, rbacRoleDBTypes, false, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = rbacRoleOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rbacRoleTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func rbacRoleBeforeInsertHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleAfterInsertHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleAfterSelectHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleBeforeUpdateHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleAfterUpdateHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleBeforeDeleteHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleAfterDeleteHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleBeforeUpsertHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func rbacRoleAfterUpsertHook(e boil.Executor, o *RbacRole) error {
	*o = RbacRole{}
	return nil
}

func testRbacRolesHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &RbacRole{}
	o := &RbacRole{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RbacRole object: %s", err)
	}

	AddRbacRoleHook(boil.BeforeInsertHook, rbacRoleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	rbacRoleBeforeInsertHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.AfterInsertHook, rbacRoleAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	rbacRoleAfterInsertHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.AfterSelectHook, rbacRoleAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	rbacRoleAfterSelectHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.BeforeUpdateHook, rbacRoleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	rbacRoleBeforeUpdateHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.AfterUpdateHook, rbacRoleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	rbacRoleAfterUpdateHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.BeforeDeleteHook, rbacRoleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	rbacRoleBeforeDeleteHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.AfterDeleteHook, rbacRoleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	rbacRoleAfterDeleteHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.BeforeUpsertHook, rbacRoleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	rbacRoleBeforeUpsertHooks = []RbacRoleHook{}

	AddRbacRoleHook(boil.AfterUpsertHook, rbacRoleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	rbacRoleAfterUpsertHooks = []RbacRoleHook{}
}

func testRbacRolesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRbacRolesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(rbacRoleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRbacRolesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testRbacRolesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RbacRoleSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testRbacRolesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RbacRoles().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rbacRoleDBTypes = map[string]string{`ID`: `int`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`, `DeletedAt`: `timestamp`, `Name`: `varchar`, `AppID`: `int`, `DefaultScope`: `int`}
	_               = bytes.MinRead
)

func testRbacRolesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rbacRolePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rbacRoleAllColumns) == len(rbacRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRbacRolesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rbacRoleAllColumns) == len(rbacRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RbacRole{}
	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rbacRoleDBTypes, true, rbacRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rbacRoleAllColumns, rbacRolePrimaryKeyColumns) {
		fields = rbacRoleAllColumns
	} else {
		fields = strmangle.SetComplement(
			rbacRoleAllColumns,
			rbacRolePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RbacRoleSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRbacRolesUpsert(t *testing.T) {
	t.Parallel()

	if len(rbacRoleAllColumns) == len(rbacRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRbacRoleUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RbacRole{}
	if err = randomize.Struct(seed, &o, rbacRoleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RbacRole: %s", err)
	}

	count, err := RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rbacRoleDBTypes, false, rbacRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacRole struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RbacRole: %s", err)
	}

	count, err = RbacRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
