// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// RbacRole is an object representing the database table.
type RbacRole struct {
	ID           uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt    null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	Name         string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	AppID        uint      `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`
	DefaultScope null.Uint `boil:"default_scope" json:"default_scope,omitempty" toml:"default_scope" yaml:"default_scope,omitempty"`

	R *rbacRoleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rbacRoleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RbacRoleColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    string
	Name         string
	AppID        string
	DefaultScope string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
	Name:         "name",
	AppID:        "app_id",
	DefaultScope: "default_scope",
}

// Generated where

var RbacRoleWhere = struct {
	ID           whereHelperuint
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
	DeletedAt    whereHelpernull_Time
	Name         whereHelperstring
	AppID        whereHelperuint
	DefaultScope whereHelpernull_Uint
}{
	ID:           whereHelperuint{field: "`rbac_roles`.`id`"},
	CreatedAt:    whereHelpernull_Time{field: "`rbac_roles`.`created_at`"},
	UpdatedAt:    whereHelpernull_Time{field: "`rbac_roles`.`updated_at`"},
	DeletedAt:    whereHelpernull_Time{field: "`rbac_roles`.`deleted_at`"},
	Name:         whereHelperstring{field: "`rbac_roles`.`name`"},
	AppID:        whereHelperuint{field: "`rbac_roles`.`app_id`"},
	DefaultScope: whereHelpernull_Uint{field: "`rbac_roles`.`default_scope`"},
}

// RbacRoleRels is where relationship names are stored.
var RbacRoleRels = struct {
}{}

// rbacRoleR is where relationships are stored.
type rbacRoleR struct {
}

// NewStruct creates a new relationship struct
func (*rbacRoleR) NewStruct() *rbacRoleR {
	return &rbacRoleR{}
}

// rbacRoleL is where Load methods for each relationship are stored.
type rbacRoleL struct{}

var (
	rbacRoleAllColumns            = []string{"id", "created_at", "updated_at", "deleted_at", "name", "app_id", "default_scope"}
	rbacRoleColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "name", "app_id", "default_scope"}
	rbacRoleColumnsWithDefault    = []string{"id"}
	rbacRolePrimaryKeyColumns     = []string{"id"}
)

type (
	// RbacRoleSlice is an alias for a slice of pointers to RbacRole.
	// This should generally be used opposed to []RbacRole.
	RbacRoleSlice []*RbacRole
	// RbacRoleHook is the signature for custom RbacRole hook methods
	RbacRoleHook func(boil.Executor, *RbacRole) error

	rbacRoleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rbacRoleType                 = reflect.TypeOf(&RbacRole{})
	rbacRoleMapping              = queries.MakeStructMapping(rbacRoleType)
	rbacRolePrimaryKeyMapping, _ = queries.BindMapping(rbacRoleType, rbacRoleMapping, rbacRolePrimaryKeyColumns)
	rbacRoleInsertCacheMut       sync.RWMutex
	rbacRoleInsertCache          = make(map[string]insertCache)
	rbacRoleUpdateCacheMut       sync.RWMutex
	rbacRoleUpdateCache          = make(map[string]updateCache)
	rbacRoleUpsertCacheMut       sync.RWMutex
	rbacRoleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var rbacRoleBeforeInsertHooks []RbacRoleHook
var rbacRoleBeforeUpdateHooks []RbacRoleHook
var rbacRoleBeforeDeleteHooks []RbacRoleHook
var rbacRoleBeforeUpsertHooks []RbacRoleHook

var rbacRoleAfterInsertHooks []RbacRoleHook
var rbacRoleAfterSelectHooks []RbacRoleHook
var rbacRoleAfterUpdateHooks []RbacRoleHook
var rbacRoleAfterDeleteHooks []RbacRoleHook
var rbacRoleAfterUpsertHooks []RbacRoleHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RbacRole) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RbacRole) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RbacRole) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RbacRole) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RbacRole) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RbacRole) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RbacRole) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RbacRole) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RbacRole) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRbacRoleHook registers your hook function for all future operations.
func AddRbacRoleHook(hookPoint boil.HookPoint, rbacRoleHook RbacRoleHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		rbacRoleBeforeInsertHooks = append(rbacRoleBeforeInsertHooks, rbacRoleHook)
	case boil.BeforeUpdateHook:
		rbacRoleBeforeUpdateHooks = append(rbacRoleBeforeUpdateHooks, rbacRoleHook)
	case boil.BeforeDeleteHook:
		rbacRoleBeforeDeleteHooks = append(rbacRoleBeforeDeleteHooks, rbacRoleHook)
	case boil.BeforeUpsertHook:
		rbacRoleBeforeUpsertHooks = append(rbacRoleBeforeUpsertHooks, rbacRoleHook)
	case boil.AfterInsertHook:
		rbacRoleAfterInsertHooks = append(rbacRoleAfterInsertHooks, rbacRoleHook)
	case boil.AfterSelectHook:
		rbacRoleAfterSelectHooks = append(rbacRoleAfterSelectHooks, rbacRoleHook)
	case boil.AfterUpdateHook:
		rbacRoleAfterUpdateHooks = append(rbacRoleAfterUpdateHooks, rbacRoleHook)
	case boil.AfterDeleteHook:
		rbacRoleAfterDeleteHooks = append(rbacRoleAfterDeleteHooks, rbacRoleHook)
	case boil.AfterUpsertHook:
		rbacRoleAfterUpsertHooks = append(rbacRoleAfterUpsertHooks, rbacRoleHook)
	}
}

// One returns a single rbacRole record from the query.
func (q rbacRoleQuery) One(exec boil.Executor) (*RbacRole, error) {
	o := &RbacRole{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for rbac_roles")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RbacRole records from the query.
func (q rbacRoleQuery) All(exec boil.Executor) (RbacRoleSlice, error) {
	var o []*RbacRole

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RbacRole slice")
	}

	if len(rbacRoleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RbacRole records in the query.
func (q rbacRoleQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count rbac_roles rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q rbacRoleQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if rbac_roles exists")
	}

	return count > 0, nil
}

// RbacRoles retrieves all the records using an executor.
func RbacRoles(mods ...qm.QueryMod) rbacRoleQuery {
	mods = append(mods, qm.From("`rbac_roles`"))
	return rbacRoleQuery{NewQuery(mods...)}
}

// FindRbacRole retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRbacRole(exec boil.Executor, iD uint, selectCols ...string) (*RbacRole, error) {
	rbacRoleObj := &RbacRole{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `rbac_roles` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, rbacRoleObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from rbac_roles")
	}

	return rbacRoleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RbacRole) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_roles provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacRoleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rbacRoleInsertCacheMut.RLock()
	cache, cached := rbacRoleInsertCache[key]
	rbacRoleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rbacRoleAllColumns,
			rbacRoleColumnsWithDefault,
			rbacRoleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `rbac_roles` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `rbac_roles` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `rbac_roles` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, rbacRolePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into rbac_roles")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacRoleMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_roles")
	}

CacheNoHooks:
	if !cached {
		rbacRoleInsertCacheMut.Lock()
		rbacRoleInsertCache[key] = cache
		rbacRoleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the RbacRole.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RbacRole) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	rbacRoleUpdateCacheMut.RLock()
	cache, cached := rbacRoleUpdateCache[key]
	rbacRoleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rbacRoleAllColumns,
			rbacRolePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update rbac_roles, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `rbac_roles` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, rbacRolePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, append(wl, rbacRolePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update rbac_roles row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for rbac_roles")
	}

	if !cached {
		rbacRoleUpdateCacheMut.Lock()
		rbacRoleUpdateCache[key] = cache
		rbacRoleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q rbacRoleQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for rbac_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for rbac_roles")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RbacRoleSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `rbac_roles` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRolePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in rbacRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all rbacRole")
	}
	return rowsAff, nil
}

var mySQLRbacRoleUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RbacRole) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_roles provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacRoleColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLRbacRoleUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rbacRoleUpsertCacheMut.RLock()
	cache, cached := rbacRoleUpsertCache[key]
	rbacRoleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			rbacRoleAllColumns,
			rbacRoleColumnsWithDefault,
			rbacRoleColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			rbacRoleAllColumns,
			rbacRolePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert rbac_roles, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "rbac_roles", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `rbac_roles` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for rbac_roles")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacRoleMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(rbacRoleType, rbacRoleMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for rbac_roles")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_roles")
	}

CacheNoHooks:
	if !cached {
		rbacRoleUpsertCacheMut.Lock()
		rbacRoleUpsertCache[key] = cache
		rbacRoleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single RbacRole record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RbacRole) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RbacRole provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rbacRolePrimaryKeyMapping)
	sql := "DELETE FROM `rbac_roles` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from rbac_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for rbac_roles")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q rbacRoleQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no rbacRoleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbac_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_roles")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RbacRoleSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(rbacRoleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `rbac_roles` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRolePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbacRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_roles")
	}

	if len(rbacRoleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RbacRole) Reload(exec boil.Executor) error {
	ret, err := FindRbacRole(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RbacRoleSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RbacRoleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `rbac_roles`.* FROM `rbac_roles` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRolePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RbacRoleSlice")
	}

	*o = slice

	return nil
}

// RbacRoleExists checks if the RbacRole row exists.
func RbacRoleExists(exec boil.Executor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `rbac_roles` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if rbac_roles exists")
	}

	return exists, nil
}
