// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// RbacRoleScope is an object representing the database table.
type RbacRoleScope struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	RoleID    uint      `boil:"role_id" json:"role_id" toml:"role_id" yaml:"role_id"`
	ScopeID   uint      `boil:"scope_id" json:"scope_id" toml:"scope_id" yaml:"scope_id"`

	R *rbacRoleScopeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rbacRoleScopeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RbacRoleScopeColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	RoleID    string
	ScopeID   string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	RoleID:    "role_id",
	ScopeID:   "scope_id",
}

// Generated where

var RbacRoleScopeWhere = struct {
	ID        whereHelperuint
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
	DeletedAt whereHelpernull_Time
	RoleID    whereHelperuint
	ScopeID   whereHelperuint
}{
	ID:        whereHelperuint{field: "`rbac_role_scopes`.`id`"},
	CreatedAt: whereHelpernull_Time{field: "`rbac_role_scopes`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`rbac_role_scopes`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`rbac_role_scopes`.`deleted_at`"},
	RoleID:    whereHelperuint{field: "`rbac_role_scopes`.`role_id`"},
	ScopeID:   whereHelperuint{field: "`rbac_role_scopes`.`scope_id`"},
}

// RbacRoleScopeRels is where relationship names are stored.
var RbacRoleScopeRels = struct {
}{}

// rbacRoleScopeR is where relationships are stored.
type rbacRoleScopeR struct {
}

// NewStruct creates a new relationship struct
func (*rbacRoleScopeR) NewStruct() *rbacRoleScopeR {
	return &rbacRoleScopeR{}
}

// rbacRoleScopeL is where Load methods for each relationship are stored.
type rbacRoleScopeL struct{}

var (
	rbacRoleScopeAllColumns            = []string{"id", "created_at", "updated_at", "deleted_at", "role_id", "scope_id"}
	rbacRoleScopeColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "role_id", "scope_id"}
	rbacRoleScopeColumnsWithDefault    = []string{"id"}
	rbacRoleScopePrimaryKeyColumns     = []string{"id"}
)

type (
	// RbacRoleScopeSlice is an alias for a slice of pointers to RbacRoleScope.
	// This should generally be used opposed to []RbacRoleScope.
	RbacRoleScopeSlice []*RbacRoleScope
	// RbacRoleScopeHook is the signature for custom RbacRoleScope hook methods
	RbacRoleScopeHook func(boil.Executor, *RbacRoleScope) error

	rbacRoleScopeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rbacRoleScopeType                 = reflect.TypeOf(&RbacRoleScope{})
	rbacRoleScopeMapping              = queries.MakeStructMapping(rbacRoleScopeType)
	rbacRoleScopePrimaryKeyMapping, _ = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, rbacRoleScopePrimaryKeyColumns)
	rbacRoleScopeInsertCacheMut       sync.RWMutex
	rbacRoleScopeInsertCache          = make(map[string]insertCache)
	rbacRoleScopeUpdateCacheMut       sync.RWMutex
	rbacRoleScopeUpdateCache          = make(map[string]updateCache)
	rbacRoleScopeUpsertCacheMut       sync.RWMutex
	rbacRoleScopeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var rbacRoleScopeBeforeInsertHooks []RbacRoleScopeHook
var rbacRoleScopeBeforeUpdateHooks []RbacRoleScopeHook
var rbacRoleScopeBeforeDeleteHooks []RbacRoleScopeHook
var rbacRoleScopeBeforeUpsertHooks []RbacRoleScopeHook

var rbacRoleScopeAfterInsertHooks []RbacRoleScopeHook
var rbacRoleScopeAfterSelectHooks []RbacRoleScopeHook
var rbacRoleScopeAfterUpdateHooks []RbacRoleScopeHook
var rbacRoleScopeAfterDeleteHooks []RbacRoleScopeHook
var rbacRoleScopeAfterUpsertHooks []RbacRoleScopeHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RbacRoleScope) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RbacRoleScope) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RbacRoleScope) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RbacRoleScope) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RbacRoleScope) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RbacRoleScope) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RbacRoleScope) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RbacRoleScope) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RbacRoleScope) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacRoleScopeAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRbacRoleScopeHook registers your hook function for all future operations.
func AddRbacRoleScopeHook(hookPoint boil.HookPoint, rbacRoleScopeHook RbacRoleScopeHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		rbacRoleScopeBeforeInsertHooks = append(rbacRoleScopeBeforeInsertHooks, rbacRoleScopeHook)
	case boil.BeforeUpdateHook:
		rbacRoleScopeBeforeUpdateHooks = append(rbacRoleScopeBeforeUpdateHooks, rbacRoleScopeHook)
	case boil.BeforeDeleteHook:
		rbacRoleScopeBeforeDeleteHooks = append(rbacRoleScopeBeforeDeleteHooks, rbacRoleScopeHook)
	case boil.BeforeUpsertHook:
		rbacRoleScopeBeforeUpsertHooks = append(rbacRoleScopeBeforeUpsertHooks, rbacRoleScopeHook)
	case boil.AfterInsertHook:
		rbacRoleScopeAfterInsertHooks = append(rbacRoleScopeAfterInsertHooks, rbacRoleScopeHook)
	case boil.AfterSelectHook:
		rbacRoleScopeAfterSelectHooks = append(rbacRoleScopeAfterSelectHooks, rbacRoleScopeHook)
	case boil.AfterUpdateHook:
		rbacRoleScopeAfterUpdateHooks = append(rbacRoleScopeAfterUpdateHooks, rbacRoleScopeHook)
	case boil.AfterDeleteHook:
		rbacRoleScopeAfterDeleteHooks = append(rbacRoleScopeAfterDeleteHooks, rbacRoleScopeHook)
	case boil.AfterUpsertHook:
		rbacRoleScopeAfterUpsertHooks = append(rbacRoleScopeAfterUpsertHooks, rbacRoleScopeHook)
	}
}

// One returns a single rbacRoleScope record from the query.
func (q rbacRoleScopeQuery) One(exec boil.Executor) (*RbacRoleScope, error) {
	o := &RbacRoleScope{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for rbac_role_scopes")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RbacRoleScope records from the query.
func (q rbacRoleScopeQuery) All(exec boil.Executor) (RbacRoleScopeSlice, error) {
	var o []*RbacRoleScope

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RbacRoleScope slice")
	}

	if len(rbacRoleScopeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RbacRoleScope records in the query.
func (q rbacRoleScopeQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count rbac_role_scopes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q rbacRoleScopeQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if rbac_role_scopes exists")
	}

	return count > 0, nil
}

// RbacRoleScopes retrieves all the records using an executor.
func RbacRoleScopes(mods ...qm.QueryMod) rbacRoleScopeQuery {
	mods = append(mods, qm.From("`rbac_role_scopes`"))
	return rbacRoleScopeQuery{NewQuery(mods...)}
}

// FindRbacRoleScope retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRbacRoleScope(exec boil.Executor, iD uint, selectCols ...string) (*RbacRoleScope, error) {
	rbacRoleScopeObj := &RbacRoleScope{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `rbac_role_scopes` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, rbacRoleScopeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from rbac_role_scopes")
	}

	return rbacRoleScopeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RbacRoleScope) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_role_scopes provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacRoleScopeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rbacRoleScopeInsertCacheMut.RLock()
	cache, cached := rbacRoleScopeInsertCache[key]
	rbacRoleScopeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rbacRoleScopeAllColumns,
			rbacRoleScopeColumnsWithDefault,
			rbacRoleScopeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `rbac_role_scopes` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `rbac_role_scopes` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `rbac_role_scopes` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, rbacRoleScopePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into rbac_role_scopes")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacRoleScopeMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_role_scopes")
	}

CacheNoHooks:
	if !cached {
		rbacRoleScopeInsertCacheMut.Lock()
		rbacRoleScopeInsertCache[key] = cache
		rbacRoleScopeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the RbacRoleScope.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RbacRoleScope) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	rbacRoleScopeUpdateCacheMut.RLock()
	cache, cached := rbacRoleScopeUpdateCache[key]
	rbacRoleScopeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rbacRoleScopeAllColumns,
			rbacRoleScopePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update rbac_role_scopes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `rbac_role_scopes` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, rbacRoleScopePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, append(wl, rbacRoleScopePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update rbac_role_scopes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for rbac_role_scopes")
	}

	if !cached {
		rbacRoleScopeUpdateCacheMut.Lock()
		rbacRoleScopeUpdateCache[key] = cache
		rbacRoleScopeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q rbacRoleScopeQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for rbac_role_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for rbac_role_scopes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RbacRoleScopeSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRoleScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `rbac_role_scopes` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRoleScopePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in rbacRoleScope slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all rbacRoleScope")
	}
	return rowsAff, nil
}

var mySQLRbacRoleScopeUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RbacRoleScope) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_role_scopes provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacRoleScopeColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLRbacRoleScopeUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rbacRoleScopeUpsertCacheMut.RLock()
	cache, cached := rbacRoleScopeUpsertCache[key]
	rbacRoleScopeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			rbacRoleScopeAllColumns,
			rbacRoleScopeColumnsWithDefault,
			rbacRoleScopeColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			rbacRoleScopeAllColumns,
			rbacRoleScopePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert rbac_role_scopes, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "rbac_role_scopes", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `rbac_role_scopes` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for rbac_role_scopes")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacRoleScopeMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(rbacRoleScopeType, rbacRoleScopeMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for rbac_role_scopes")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_role_scopes")
	}

CacheNoHooks:
	if !cached {
		rbacRoleScopeUpsertCacheMut.Lock()
		rbacRoleScopeUpsertCache[key] = cache
		rbacRoleScopeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single RbacRoleScope record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RbacRoleScope) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RbacRoleScope provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rbacRoleScopePrimaryKeyMapping)
	sql := "DELETE FROM `rbac_role_scopes` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from rbac_role_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for rbac_role_scopes")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q rbacRoleScopeQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no rbacRoleScopeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbac_role_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_role_scopes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RbacRoleScopeSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(rbacRoleScopeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRoleScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `rbac_role_scopes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRoleScopePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbacRoleScope slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_role_scopes")
	}

	if len(rbacRoleScopeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RbacRoleScope) Reload(exec boil.Executor) error {
	ret, err := FindRbacRoleScope(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RbacRoleScopeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RbacRoleScopeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacRoleScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `rbac_role_scopes`.* FROM `rbac_role_scopes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacRoleScopePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RbacRoleScopeSlice")
	}

	*o = slice

	return nil
}

// RbacRoleScopeExists checks if the RbacRoleScope row exists.
func RbacRoleScopeExists(exec boil.Executor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `rbac_role_scopes` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if rbac_role_scopes exists")
	}

	return exists, nil
}
