// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRbacUserApplicationRoles(t *testing.T) {
	t.Parallel()

	query := RbacUserApplicationRoles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRbacUserApplicationRolesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacUserApplicationRolesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RbacUserApplicationRoles().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacUserApplicationRolesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RbacUserApplicationRoleSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRbacUserApplicationRolesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RbacUserApplicationRoleExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RbacUserApplicationRole exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RbacUserApplicationRoleExists to return true, but got false.")
	}
}

func testRbacUserApplicationRolesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rbacUserApplicationRoleFound, err := FindRbacUserApplicationRole(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rbacUserApplicationRoleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRbacUserApplicationRolesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RbacUserApplicationRoles().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testRbacUserApplicationRolesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RbacUserApplicationRoles().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRbacUserApplicationRolesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rbacUserApplicationRoleOne := &RbacUserApplicationRole{}
	rbacUserApplicationRoleTwo := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, rbacUserApplicationRoleOne, rbacUserApplicationRoleDBTypes, false, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}
	if err = randomize.Struct(seed, rbacUserApplicationRoleTwo, rbacUserApplicationRoleDBTypes, false, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = rbacUserApplicationRoleOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rbacUserApplicationRoleTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RbacUserApplicationRoles().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRbacUserApplicationRolesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rbacUserApplicationRoleOne := &RbacUserApplicationRole{}
	rbacUserApplicationRoleTwo := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, rbacUserApplicationRoleOne, rbacUserApplicationRoleDBTypes, false, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}
	if err = randomize.Struct(seed, rbacUserApplicationRoleTwo, rbacUserApplicationRoleDBTypes, false, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = rbacUserApplicationRoleOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rbacUserApplicationRoleTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func rbacUserApplicationRoleBeforeInsertHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleAfterInsertHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleAfterSelectHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleBeforeUpdateHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleAfterUpdateHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleBeforeDeleteHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleAfterDeleteHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleBeforeUpsertHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func rbacUserApplicationRoleAfterUpsertHook(e boil.Executor, o *RbacUserApplicationRole) error {
	*o = RbacUserApplicationRole{}
	return nil
}

func testRbacUserApplicationRolesHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &RbacUserApplicationRole{}
	o := &RbacUserApplicationRole{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole object: %s", err)
	}

	AddRbacUserApplicationRoleHook(boil.BeforeInsertHook, rbacUserApplicationRoleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleBeforeInsertHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.AfterInsertHook, rbacUserApplicationRoleAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleAfterInsertHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.AfterSelectHook, rbacUserApplicationRoleAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleAfterSelectHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.BeforeUpdateHook, rbacUserApplicationRoleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleBeforeUpdateHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.AfterUpdateHook, rbacUserApplicationRoleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleAfterUpdateHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.BeforeDeleteHook, rbacUserApplicationRoleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleBeforeDeleteHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.AfterDeleteHook, rbacUserApplicationRoleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleAfterDeleteHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.BeforeUpsertHook, rbacUserApplicationRoleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleBeforeUpsertHooks = []RbacUserApplicationRoleHook{}

	AddRbacUserApplicationRoleHook(boil.AfterUpsertHook, rbacUserApplicationRoleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	rbacUserApplicationRoleAfterUpsertHooks = []RbacUserApplicationRoleHook{}
}

func testRbacUserApplicationRolesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRbacUserApplicationRolesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(rbacUserApplicationRoleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRbacUserApplicationRolesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testRbacUserApplicationRolesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RbacUserApplicationRoleSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testRbacUserApplicationRolesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RbacUserApplicationRoles().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rbacUserApplicationRoleDBTypes = map[string]string{`ID`: `int`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`, `DeletedAt`: `timestamp`, `UserID`: `int`, `AppID`: `int`, `RoleID`: `int`}
	_                              = bytes.MinRead
)

func testRbacUserApplicationRolesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rbacUserApplicationRolePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rbacUserApplicationRoleAllColumns) == len(rbacUserApplicationRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRbacUserApplicationRolesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rbacUserApplicationRoleAllColumns) == len(rbacUserApplicationRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RbacUserApplicationRole{}
	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRoleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rbacUserApplicationRoleDBTypes, true, rbacUserApplicationRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rbacUserApplicationRoleAllColumns, rbacUserApplicationRolePrimaryKeyColumns) {
		fields = rbacUserApplicationRoleAllColumns
	} else {
		fields = strmangle.SetComplement(
			rbacUserApplicationRoleAllColumns,
			rbacUserApplicationRolePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RbacUserApplicationRoleSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRbacUserApplicationRolesUpsert(t *testing.T) {
	t.Parallel()

	if len(rbacUserApplicationRoleAllColumns) == len(rbacUserApplicationRolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRbacUserApplicationRoleUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RbacUserApplicationRole{}
	if err = randomize.Struct(seed, &o, rbacUserApplicationRoleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RbacUserApplicationRole: %s", err)
	}

	count, err := RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rbacUserApplicationRoleDBTypes, false, rbacUserApplicationRolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RbacUserApplicationRole struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RbacUserApplicationRole: %s", err)
	}

	count, err = RbacUserApplicationRoles().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
