// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// RbacScope is an object representing the database table.
type RbacScope struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	AppID     uint      `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`

	R *rbacScopeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rbacScopeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RbacScopeColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	Name      string
	AppID     string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	Name:      "name",
	AppID:     "app_id",
}

// Generated where

var RbacScopeWhere = struct {
	ID        whereHelperuint
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
	DeletedAt whereHelpernull_Time
	Name      whereHelperstring
	AppID     whereHelperuint
}{
	ID:        whereHelperuint{field: "`rbac_scopes`.`id`"},
	CreatedAt: whereHelpernull_Time{field: "`rbac_scopes`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`rbac_scopes`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`rbac_scopes`.`deleted_at`"},
	Name:      whereHelperstring{field: "`rbac_scopes`.`name`"},
	AppID:     whereHelperuint{field: "`rbac_scopes`.`app_id`"},
}

// RbacScopeRels is where relationship names are stored.
var RbacScopeRels = struct {
}{}

// rbacScopeR is where relationships are stored.
type rbacScopeR struct {
}

// NewStruct creates a new relationship struct
func (*rbacScopeR) NewStruct() *rbacScopeR {
	return &rbacScopeR{}
}

// rbacScopeL is where Load methods for each relationship are stored.
type rbacScopeL struct{}

var (
	rbacScopeAllColumns            = []string{"id", "created_at", "updated_at", "deleted_at", "name", "app_id"}
	rbacScopeColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "name", "app_id"}
	rbacScopeColumnsWithDefault    = []string{"id"}
	rbacScopePrimaryKeyColumns     = []string{"id"}
)

type (
	// RbacScopeSlice is an alias for a slice of pointers to RbacScope.
	// This should generally be used opposed to []RbacScope.
	RbacScopeSlice []*RbacScope
	// RbacScopeHook is the signature for custom RbacScope hook methods
	RbacScopeHook func(boil.Executor, *RbacScope) error

	rbacScopeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rbacScopeType                 = reflect.TypeOf(&RbacScope{})
	rbacScopeMapping              = queries.MakeStructMapping(rbacScopeType)
	rbacScopePrimaryKeyMapping, _ = queries.BindMapping(rbacScopeType, rbacScopeMapping, rbacScopePrimaryKeyColumns)
	rbacScopeInsertCacheMut       sync.RWMutex
	rbacScopeInsertCache          = make(map[string]insertCache)
	rbacScopeUpdateCacheMut       sync.RWMutex
	rbacScopeUpdateCache          = make(map[string]updateCache)
	rbacScopeUpsertCacheMut       sync.RWMutex
	rbacScopeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var rbacScopeBeforeInsertHooks []RbacScopeHook
var rbacScopeBeforeUpdateHooks []RbacScopeHook
var rbacScopeBeforeDeleteHooks []RbacScopeHook
var rbacScopeBeforeUpsertHooks []RbacScopeHook

var rbacScopeAfterInsertHooks []RbacScopeHook
var rbacScopeAfterSelectHooks []RbacScopeHook
var rbacScopeAfterUpdateHooks []RbacScopeHook
var rbacScopeAfterDeleteHooks []RbacScopeHook
var rbacScopeAfterUpsertHooks []RbacScopeHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RbacScope) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RbacScope) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RbacScope) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RbacScope) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RbacScope) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RbacScope) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RbacScope) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RbacScope) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RbacScope) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range rbacScopeAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRbacScopeHook registers your hook function for all future operations.
func AddRbacScopeHook(hookPoint boil.HookPoint, rbacScopeHook RbacScopeHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		rbacScopeBeforeInsertHooks = append(rbacScopeBeforeInsertHooks, rbacScopeHook)
	case boil.BeforeUpdateHook:
		rbacScopeBeforeUpdateHooks = append(rbacScopeBeforeUpdateHooks, rbacScopeHook)
	case boil.BeforeDeleteHook:
		rbacScopeBeforeDeleteHooks = append(rbacScopeBeforeDeleteHooks, rbacScopeHook)
	case boil.BeforeUpsertHook:
		rbacScopeBeforeUpsertHooks = append(rbacScopeBeforeUpsertHooks, rbacScopeHook)
	case boil.AfterInsertHook:
		rbacScopeAfterInsertHooks = append(rbacScopeAfterInsertHooks, rbacScopeHook)
	case boil.AfterSelectHook:
		rbacScopeAfterSelectHooks = append(rbacScopeAfterSelectHooks, rbacScopeHook)
	case boil.AfterUpdateHook:
		rbacScopeAfterUpdateHooks = append(rbacScopeAfterUpdateHooks, rbacScopeHook)
	case boil.AfterDeleteHook:
		rbacScopeAfterDeleteHooks = append(rbacScopeAfterDeleteHooks, rbacScopeHook)
	case boil.AfterUpsertHook:
		rbacScopeAfterUpsertHooks = append(rbacScopeAfterUpsertHooks, rbacScopeHook)
	}
}

// One returns a single rbacScope record from the query.
func (q rbacScopeQuery) One(exec boil.Executor) (*RbacScope, error) {
	o := &RbacScope{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for rbac_scopes")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RbacScope records from the query.
func (q rbacScopeQuery) All(exec boil.Executor) (RbacScopeSlice, error) {
	var o []*RbacScope

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RbacScope slice")
	}

	if len(rbacScopeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RbacScope records in the query.
func (q rbacScopeQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count rbac_scopes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q rbacScopeQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if rbac_scopes exists")
	}

	return count > 0, nil
}

// RbacScopes retrieves all the records using an executor.
func RbacScopes(mods ...qm.QueryMod) rbacScopeQuery {
	mods = append(mods, qm.From("`rbac_scopes`"))
	return rbacScopeQuery{NewQuery(mods...)}
}

// FindRbacScope retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRbacScope(exec boil.Executor, iD uint, selectCols ...string) (*RbacScope, error) {
	rbacScopeObj := &RbacScope{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `rbac_scopes` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, rbacScopeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from rbac_scopes")
	}

	return rbacScopeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RbacScope) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_scopes provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacScopeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rbacScopeInsertCacheMut.RLock()
	cache, cached := rbacScopeInsertCache[key]
	rbacScopeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rbacScopeAllColumns,
			rbacScopeColumnsWithDefault,
			rbacScopeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `rbac_scopes` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `rbac_scopes` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `rbac_scopes` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, rbacScopePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into rbac_scopes")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacScopeMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_scopes")
	}

CacheNoHooks:
	if !cached {
		rbacScopeInsertCacheMut.Lock()
		rbacScopeInsertCache[key] = cache
		rbacScopeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the RbacScope.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RbacScope) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	rbacScopeUpdateCacheMut.RLock()
	cache, cached := rbacScopeUpdateCache[key]
	rbacScopeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rbacScopeAllColumns,
			rbacScopePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update rbac_scopes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `rbac_scopes` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, rbacScopePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, append(wl, rbacScopePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update rbac_scopes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for rbac_scopes")
	}

	if !cached {
		rbacScopeUpdateCacheMut.Lock()
		rbacScopeUpdateCache[key] = cache
		rbacScopeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q rbacScopeQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for rbac_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for rbac_scopes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RbacScopeSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `rbac_scopes` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacScopePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in rbacScope slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all rbacScope")
	}
	return rowsAff, nil
}

var mySQLRbacScopeUniqueColumns = []string{
	"id",
	"name",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RbacScope) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rbac_scopes provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rbacScopeColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLRbacScopeUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rbacScopeUpsertCacheMut.RLock()
	cache, cached := rbacScopeUpsertCache[key]
	rbacScopeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			rbacScopeAllColumns,
			rbacScopeColumnsWithDefault,
			rbacScopeColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			rbacScopeAllColumns,
			rbacScopePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert rbac_scopes, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "rbac_scopes", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `rbac_scopes` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for rbac_scopes")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rbacScopeMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(rbacScopeType, rbacScopeMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for rbac_scopes")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rbac_scopes")
	}

CacheNoHooks:
	if !cached {
		rbacScopeUpsertCacheMut.Lock()
		rbacScopeUpsertCache[key] = cache
		rbacScopeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single RbacScope record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RbacScope) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RbacScope provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rbacScopePrimaryKeyMapping)
	sql := "DELETE FROM `rbac_scopes` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from rbac_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for rbac_scopes")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q rbacScopeQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no rbacScopeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbac_scopes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_scopes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RbacScopeSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(rbacScopeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `rbac_scopes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacScopePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rbacScope slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rbac_scopes")
	}

	if len(rbacScopeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RbacScope) Reload(exec boil.Executor) error {
	ret, err := FindRbacScope(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RbacScopeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RbacScopeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rbacScopePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `rbac_scopes`.* FROM `rbac_scopes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rbacScopePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RbacScopeSlice")
	}

	*o = slice

	return nil
}

// RbacScopeExists checks if the RbacScope row exists.
func RbacScopeExists(exec boil.Executor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `rbac_scopes` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if rbac_scopes exists")
	}

	return exists, nil
}
